# Generated by Django 2.0.6 on 2018-11-26 23:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
        ),
    ]
