# Generated by Django 2.0.6 on 2019-01-22 07:03

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20181126_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, db_index=True, upload_to='users/%y/%m/%d'),
        ),
    ]
