# Generated by Django 2.0.6 on 2019-01-22 08:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20190121_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
