# Generated by Django 2.0.6 on 2018-11-24 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('business_address', models.CharField(max_length=500)),
                ('home_address', models.CharField(max_length=500)),
                ('logo', models.ImageField(blank=True, upload_to='bizz/%y/%m/%d')),
                ('auth_image', models.ImageField(blank=True, upload_to='logo/%y/%m/%d')),
                ('market_name', models.CharField(db_index=True, max_length=300)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shop', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user',),
            },
        ),
    ]
