# Generated by Django 2.0.6 on 2018-11-24 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bizz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='name',
            new_name='business_name',
        ),
    ]
