# Generated by Django 2.0.6 on 2018-11-24 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizz', '0002_auto_20181123_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='auth_image',
            field=models.ImageField(upload_to='logo/%y/%m/%d'),
        ),
    ]
