# Generated by Django 2.0.6 on 2018-11-24 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bizz', '0004_auto_20181123_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='updated',
        ),
    ]
