# Generated by Django 2.0.6 on 2018-11-27 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizz', '0007_auto_20181124_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
