# Generated by Django 2.0.6 on 2018-11-27 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bizz', '0008_auto_20181127_1445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='user',
            new_name='owner',
        ),
    ]
