# Generated by Django 2.0.6 on 2018-11-30 06:02

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bizz', '0009_auto_20181127_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(default=datetime.datetime(2018, 11, 30, 6, 2, 11, 535807, tzinfo=utc), upload_to='products/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='product',
            name='users_like',
            field=models.ManyToManyField(blank=True, related_name='product_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
