# Generated by Django 2.0.6 on 2018-11-30 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bizz', '0012_auto_20181129_2220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='photo',
            new_name='image',
        ),
    ]
