# Generated by Django 2.0.6 on 2018-11-30 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizz', '0013_auto_20181129_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='products/%y/%m/%d'),
        ),
    ]
