# Generated by Django 2.0.6 on 2018-11-30 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bizz', '0014_auto_20181130_0008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='photo',
        ),
    ]
