# Generated by Django 2.0.6 on 2018-12-01 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizz', '0015_auto_20181130_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
