# Generated by Django 2.0.6 on 2018-12-12 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizz', '0017_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
