# Generated by Django 2.0.6 on 2018-12-12 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizz', '0018_product_total_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='total_likes',
            field=models.IntegerField(default=0),
        ),
    ]
