# Generated by Django 2.0.6 on 2018-12-17 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizz', '0019_auto_20181212_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='description',
            field=models.TextField(default='We sale ...'),
        ),
    ]
