# Generated by Django 2.0.6 on 2018-12-18 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizz', '0020_shop_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.FileField(default='', upload_to='videos/%y/%m/%d'),
        ),
    ]
