# Generated by Django 2.0.6 on 2018-12-18 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizz', '0021_product_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='video',
            field=models.FileField(blank=True, default='', null=True, upload_to='videos/%y/%m/%d', verbose_name=''),
        ),
    ]
