# Generated by Django 2.0.6 on 2018-12-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizz', '0025_auto_20181219_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='', max_length=500, unique_for_date='created'),
        ),
    ]
