# Generated by Django 2.0.6 on 2018-12-24 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bizz', '0026_auto_20181224_0852'),
        ('bizz', '0026_auto_20181219_0657'),
    ]

    operations = [
    ]
