# Generated by Django 2.0.6 on 2019-01-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizz', '0027_merge_20181224_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='business_address',
            field=models.CharField(choices=[('farmcenter', 'FarmCenter')], default='farmcenter', max_length=20),
        ),
    ]
