# Generated by Django 2.0.6 on 2019-01-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizz', '0028_auto_20190115_0837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='auth_image',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='market_name',
        ),
        migrations.AddField(
            model_name='shop',
            name='shop_address',
            field=models.CharField(db_index=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='shop',
            name='business_address',
            field=models.CharField(choices=[('farmcenter', 'FarmCenter'), ('kwari', 'Kwari'), ('beirut', 'Beirut'), ('wambai', 'Wambai')], default='farmcenter', max_length=20),
        ),
    ]
