# Generated by Django 2.0.6 on 2019-01-22 06:54

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bizz', '0029_auto_20190115_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='products/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='business_address',
            field=models.CharField(choices=[('farmcenter', 'FarmCenter'), ('kwari', 'Kwari'), ('beirut', 'Beirut'), ('wambai', 'Wambai'), ('private', 'Private')], default='farmcenter', max_length=20),
        ),
    ]
