# Generated by Django 2.0.6 on 2019-01-22 06:57

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bizz', '0030_auto_20190121_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='logo',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to='bizz/%y/%m/%d'),
        ),
    ]
