# Generated by Django 2.0.6 on 2019-01-31 10:52

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bizz', '0031_auto_20190121_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo1',
            field=sorl.thumbnail.fields.ImageField(blank=True, default='', null=True, upload_to='products/%y/%m/%d'),
        ),
        migrations.AddField(
            model_name='product',
            name='photo2',
            field=sorl.thumbnail.fields.ImageField(blank=True, default='', null=True, upload_to='products/%y/%m/%d'),
        ),
        migrations.AddField(
            model_name='product',
            name='photo3',
            field=sorl.thumbnail.fields.ImageField(blank=True, default='', null=True, upload_to='products/%y/%m/%d'),
        ),
    ]
