# Generated by Django 2.0.6 on 2019-03-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizz', '0039_remove_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='text', max_length=250),
        ),
    ]
