# Generated by Django 2.0.6 on 2019-03-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizz', '0041_auto_20190306_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='Bank',
            field=models.CharField(choices=[('Access Bank', 'Access Bank'), ('First Bank', 'First Bank'), ('Guaranty Trust Bank', 'Guaranty Trust Bank'), ('United Bank of Africa UBA', 'United Bank of Africa UBA'), ('Zenith Bank', 'Zenith Bank'), ('JAIZ Bank', 'JAIZ BANK')], default='Access Bank', max_length=20),
        ),
    ]
