# Generated by Django 2.0.6 on 2019-03-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizz', '0042_shop_bank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='message',
            new_name='introduction',
        ),
        migrations.AddField(
            model_name='post',
            name='paragraph_1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='paragraph_2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='paragraph_3',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='paragraph_4',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='paragraph_5',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='', max_length=250),
        ),
    ]
