# Generated by Django 2.0.6 on 2019-03-12 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizz', '0043_auto_20190311_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='paragraph_2',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='paragraph_3',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='paragraph_4',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='paragraph_5',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
