# Generated by Django 2.0.6 on 2019-03-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizz', '0047_auto_20190315_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='account_number',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
    ]
