# Generated by Django 2.0.6 on 2019-03-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizz', '0048_auto_20190315_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='account_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
