# Generated by Django 2.0.6 on 2019-03-23 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizz', '0049_auto_20190315_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('clothing', 'Clothing'), ('food', 'Food')], default='clothing', max_length=20),
        ),
    ]
