# Generated by Django 2.0.6 on 2019-03-24 00:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bizz', '0050_auto_20190323_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='Governor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('party', models.CharField(max_length=500)),
                ('image', models.FileField(upload_to='election/%y/%m/%d')),
                ('party_logo', models.FileField(upload_to='election_logo/%y/%m/%d')),
                ('counts', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Supporter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supporters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
