# Generated by Django 2.0.6 on 2019-03-24 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizz', '0051_governor_supporter'),
    ]

    operations = [
        migrations.AddField(
            model_name='governor',
            name='percent',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='governor',
            name='counts',
            field=models.DecimalField(decimal_places=0, max_digits=7),
        ),
    ]
