# Generated by Django 2.0.6 on 2019-03-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizz', '0053_product_users_hate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='introduction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='paragraph_1',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
