# Generated by Django 2.0.6 on 2019-03-29 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizz', '0054_auto_20190325_2335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='paragraph_1',
            new_name='post',
        ),
        migrations.AlterField(
            model_name='shop',
            name='account_name',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
