# Generated by Django 2.0.6 on 2019-04-18 19:28

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bizz', '0060_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo0',
            field=sorl.thumbnail.fields.ImageField(blank=True, default='', null=True, upload_to='products/%y/%m/%d'),
        ),
    ]
