# Generated by Django 2.0.6 on 2019-04-18 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizz', '0061_product_photo0'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='payment_link',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
