# Generated by Django 2.0.6 on 2019-04-18 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizz', '0062_product_payment_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='payment_link',
            field=models.CharField(blank=True, default='', max_length=10000),
        ),
    ]
