# Generated by Django 2.0.6 on 2019-04-18 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizz', '0063_auto_20190418_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='payment_link',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
