# Generated by Django 2.0.6 on 2018-12-31 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20181230_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(choices=[('kano', 'Kano')], default='kano', max_length=15),
        ),
    ]
