# Generated by Django 2.0.6 on 2019-02-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20181230_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '3')], default=1, max_length=5),
        ),
    ]
