# Generated by Django 2.0.6 on 2019-03-01 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_order_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product',
            new_name='pproduct',
        ),
    ]
