# Generated by Django 2.0.6 on 2019-03-15 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
