# Generated by Django 2.0.6 on 2019-03-23 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_order_discount_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(choices=[('kano', 'Kano'), ('bauchi', 'Bauchi')], default='kano', max_length=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15')], default='1', max_length=5),
        ),
    ]
